version: 2.1
executors:
  generic-executor:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/project
    environment:
      IMAGE_REGISTRY: ""
      IMAGE_REPO: "gwilliam0ucar"
      IMAGE_NAME: "test"
      WORKSPACE: "/tmp/workspace"
      LOCAL_BIN: "/tmp/workspace/bin"
      STATEDIR: "/tmp/workspace/state"
      INIT_RC: "/tmp/workspace/state/init.rc"
      DIDACTIC_REPO: "git@github.com:gwilliam-ucar-edu/didactic.git"

jobs:

  build-nondeployable:
    executor: generic-executor
    steps:
      - setup_remote_docker

      - run:
          name: "Build"
          command: |
              echo docker build .

  initialize-cd:
    executor: generic-executor
    steps:
      - checkout

      - run:
          name: "Initialize workspace"
          command: |
              mkdir -p ${WORKSPACE}
              git clone -v --branch ${DIDACTIC_TAG:-master} --depth 1 \
                  ${DIDACTIC_REPO} ${WORKSPACE}
              mkdir -p ${WORKSPACE}/state
              ${WORKSPACE}/bin/didactic-init
              . ${INIT_RC}
              circle-debug-dump

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bin
            - state

  build-deployable:
    executor: generic-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: "Conditionally build, push, and register image"
          command: |
              . ${INIT_RC}
              if [[ -z "${IMAGE_TAG}" ]] ; then
                  docker-cibuild --metadata=${IMAGE_METADATA} \
                                 --image-name=${IMAGE_NAME} .
                  didactic-cl --register-image
              else
                  echo "Image ${IMAGE_NAME}:${IMAGE_TAG} already exists"
              fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - state

  deploy:
    executor: generic-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: "Pull image, tag and repush, log"
          command: |
              . ${INIT_RC}
              if didactic-cl --check-authorization ; then
                  docker-tag-push \
                   ${IMAGE_NAME}:${IMAGE_TAG} \
                   ${IMAGE_PATH} ${DEPLOY_TAGS}
                  didactic-cl --register-deployment
              else
                  didactic-cl --request-authorization
              fi

workflows:
  version: 2
  build:
    jobs:
      - build-nondeployable:
          filters:
            branches:
              only:
                - master
      - initialize-cd:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^\d+\.\d+\.\d+.*$/
      - build-deployable:
          requires:
            - initialize-cd
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+.*$/
      - deploy:
          requires:
            - build-deployable
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+.*/


