version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7.2-cli

jobs:
  initialize:
    executor: my-executor
    steps:
      - checkout

      - run:
          name: "Install citools"
          command: |
            DIR=`pwd`
            cd $HOME
            git clone --depth 1 git@github.com:NCAR/citools.git bin
            cd "$DIR"

      - run :
          name: "Dump debug Info"
          command: |
            PATH="$HOME/bin:$PATH" export PATH
            circle-debug-dump            

      - run:
          name: "Validate/fix GitHub release"
          command: |
            PATH="$HOME/bin:$PATH" export PATH
            if [ ":$CIRCLE_TAG" ] ; then
                normalize-github-release
            fi

  build-only:
    executor: my-executor
    steps:
      - run:
          name: "Build"
          command: |
            echo "Mock build step"

workflows:
  version: 2
  build:
    jobs:
      - initialize:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^[vV]?\d+\.\d+\.\d.*$/
      - build-only:
          requires:
            - initialize
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[vV]?\d+\.\d+\.\d.*$/
