version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7-cli

jobs:
  say-hello:
    executor: my-executor
    steps:
      - run:
          name: "Say Hello"
          command: |
            echo Hello!

  say-howdy:
    executor: my-executor

    steps:
      - run:
          name: "Say Howdy"
          command: |
            echo Howdy!

  build-push:
    executor: my-executor

    steps:
      - checkout

      - run:
          name: "Gather Debug Info"
          command: |
            echo PWD=`pwd`
            echo HOME="$HOME"
            echo "ls -la .:"
            ls -la .
            echo "ls -la $HOME:"
            ls -la $HOME
            echo printenv:
            printenv | sed -e 's/PASSWORD=.*/PASSWORD=----/' \
                           -e 's/PRIVATE_KEY=.*/PRIVATE_KEY=----/' \
                           -e 's/SECRET_ACCESS_KEY=.*/SECRET_ACCESS_KEY=----/' \
                           -e 's/GH_TOKEN=.*/GH_TOKEN=----/'
            echo git status:
            git status
            echo git rev-list HEAD
            git rev-list HEAD
            echo git tag --list
            git tag --list
            echo git tag --list --points-at \$CIRCLE_SHA1
            git tag --list --points-at $CIRCLE_SHA1

      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote citools

      - setup_remote_docker

      - run:
          name: "Build image"
          command: |
            citools/docker-build -t $CIRCLE_PROJECT_REPONAME:latest .

workflows:
  build-push:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
