version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7-cli

jobs:
  say-hello:
    executor: my-executor
    steps:
      - run:
          name: "Say Hello"
          command: |
            echo Hello!

  say-howdy:
    executor: my-executor

    steps:
      - run:
          name: "Say Howdy"
          command: |
            echo Howdy!

  build-push:
    executor: my-executor

    parameters:
      scheduled-run:
        type: boolean
        default: false
    steps:
      - when:
          # scheduled workflow initializes
          condition: << parameters.scheduled-run >>
          steps:
            - attach_workspace:
                at: /tmp/workspace
      - unless:
          condition: << parameters.scheduled-run >>
          steps:
            - run:
                command: |
                  mkdir -p /tmp/workspace/rc
                  echo : >/tmp/workspace/rc/build-push

      - checkout

      - run:
          name: "Gather Debug Info"
          command: |
            echo PWD=`pwd`
            echo HOME="$HOME"
            echo "ls -la .:"
            ls -la .
            echo "ls -la $HOME:"
            ls -la $HOME
            echo printenv:
            printenv | sed -e 's/PASSWORD=.*/PASSWORD=----/' \
                           -e 's/PRIVATE_KEY=.*/PRIVATE_KEY=----/' \
                           -e 's/SECRET_ACCESS_KEY=.*/SECRET_ACCESS_KEY=----/' \
                           -e 's/GH_TOKEN=.*/GH_TOKEN=----/'
            echo git status:
            git status
            echo git rev-list HEAD
            git rev-list HEAD
            echo git tag --list
            git tag --list
            echo git tag --list --points-at \$CIRCLE_SHA1
            git tag --list --points-at $CIRCLE_SHA1

      - run:
          name: "Pull submodules"
          command: |
            . /tmp/workspace/rc/build-push
            git submodule init
            git submodule update --remote citools

      - setup_remote_docker

      - run:
          name: "Build image"
          command: |
            . /tmp/workspace/rc/build-push
            citools/docker-build -t $CIRCLE_PROJECT_REPONAME:latest .

      - run:
          name: "Tag image"
          command: |
            . /tmp/workspace/rc/build-push
            docker tag $CIRCLE_PROJECT_REPONAME:latest ncar/$CIRCLE_PROJECT_REPONAME:latest

      - run:
          name: "Push to Docker hub"
          command: |
            . /tmp/workspace/rc/build-push
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker push ncar/$CIRCLE_PROJECT_REPONAME:latest

      - run:
          name: "Store image info in git branch"
          command: |
            . /tmp/workspace/rc/build-push
            bname=deployment-$CIRCLE_SHA1
            git config user.email "sweg-ci@ucar.edu"
            git config user.name "SWEG CI Service User"
            git checkout -b $bname
            mkdir $bname
            docker inspect $CIRCLE_PROJECT_REPONAME:latest >img.tmp
            jq -r '.[0].Id' <img.tmp >$bname/image.digest
            jq '.[0].ContainerConfig.Labels' <img.tmp >labels.tmp
            jq -r '."base.digest"' labels.tmp > $bname/base.digest
            jq -r '."base.tag"' labels.tmp > $bname/base.tag
            git add $bname/*
            git commit -m "build $CIRCLE_BUILD_NUM"
            git push origin $bname

workflows:
  build-push:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
