version: 2.1
executors:
  generic-executor:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/project
    environment:
      IMAGE_NAME: "gwilliam0ucar/test"
      WORKSPACE: "/tmp/workspace"
      INIT_RC: "/tmp/workspace/state/init.rc"
      PRERELEASE_ENVIRONMENTS: "test staging"
      PRODUCTION_ENVIRONMENT: "production"

jobs:
  initialize:
    executor: generic-executor
    steps:
      - checkout

      - run:
          name: "Initialize workspace"
          command: |
              mkdir -p ${WORKSPACE}/bin ${WORKSPACE}/state
              git clone -v --branch ${CITOOLS_TAG:-master} --depth 1 git@github.com:NCAR/citools.git ${WORKSPACE}/bin
              ${WORKSPACE}/bin/circle-env ${INIT_RC}
              . ${INIT_RC}
              circle-install-tools ${WORKSPACE}/bin
              circle-docker-login-init ${IMAGE_NAME}
              echo cicada init

      - run:
          name: "Show environment, workspace"
          command: |
              cat ${INIT_RC}
              . ${INIT_RC}
              echo "Environment variables:"
              ${WORKSPACE}/bin/circle-printenv
              echo
              echo "${WORKSPACE}:"
              ls -lR ${WORKSPACE}

      - persist_to_workspace:
          root: workspace
          paths:
            - bin
            - state

  build-nondeployable:
    executor: generic-executor
    steps:
      - setup_remote_docker

      - run:
          name: "Build"
          command: |
              echo docker build .

  build-deployable:
    executor: generic-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: "Build and push image, register image metadata"
          command: |
              . ${INIT_RC}
              echo "Build deployable..."

      - persist_to_workspace:
          root: workspace
          paths:
            - state

  deploy:
    executor: generic-executor
    steps:
      - attach_workspace:
          at: workspace

      - setup_remote_docker

      - run:
          name: "Pull image, tag and repush, log"
          command: |
              . ${INIT_RC}
              echo "deploy..."

workflows:
  version: 2
  build:
    jobs:
      - initialize:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^[vV]?\d+\.\d+\.\d+.*$/
      - build-nondeployable:
          requires:
            - initialize
          filters:
            branches:
              only:
                - master
      - build-deployable:
          requires:
            - initialize
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+.*$/
      - deploy-hold:
          type: approval
          requires:
            - build-deployable
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+(((-staging)?(\+.*)?)|((-[^+]+)?\+newbase.*))$/
      - deploy:
          requires:
            - deploy-hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+.*/


